### ISSUE TITLE
Api editar perfil de empresa

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#141]
Se rerquiere que al editar el prefil de la empresa sea posible el envio de una pfp

**Comment by markalbrand56** [comment]
Corregido

Ejemplo de uso:
{
    "nombre": "pruebaEmpresa",
    "detalles": "Empresa de prueba",
    "correo": "prueba@prueba",
    "telefono": "98985656",
    "foto": "foto actualizada"
}
