### ISSUE TITLE
Emisor del mensaje chat

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#148]
El emisor del chat se esta regresando mal del backend 
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/face6342-bad5-4aca-870f-2187ba32d64f)
Ya que no coincide el id del emisor con el nombre del emisor

**Comment by angelcast2002** [comment]
Pasa lo mismo con el receptor

**Comment by Diego2250** [comment]
corregido

**Comment by angelcast2002** [comment]
El nombre sigue mal :(

**Comment by Diego2250** [comment]
Ya
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/7f85f235-7307-40ec-9921-6bcb3b419014)

**Comment by Diego2250** [comment]
Se quitó la foto del receptor porque no la veia necesaria
