### ISSUE TITLE
Obtener mensajes

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#153]
El api de obtener los mensajes para un chat dado de un receptor y emisor ([POST] api/messages/get), no regresa todos los mensajes del chat, solo regresa los mensajes del emisor, nunca regresa los del receptor, es decir solo da los mensajes que el usuario envia, nunca los que recibe

**Comment by Diego2250** [comment]
Ya
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/027b9c73-fbba-48ac-8d4a-e9502a2c1a79)
