### ISSUE TITLE
Emisor

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#160]
Agregar el emisor del mensaje en el api getLastChats

**Comment by Diego2250** [comment]
Eso ya esta? es el campo user_id y el user_name
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/c299efcb-5e85-4262-b3a1-f57c56ea8e48)

**Comment by angelcast2002** [comment]
Me refiero a que salga el emisor del ultimo mensaje, para poder mejorar el front, 
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/94d325a6-ab1d-4a36-b563-44228d3e80fa)
por ejemplo aqui el ultimo mensaje fue mio, pero la info del getLast tiene nada mas con quien estoy hablando, me gustaria que saliera que el emisor fui yo, o en otro caso la empresa con la que estoy hablando.
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/df964210-c2d1-410d-a671-d84e803c8f9a)

**Comment by Diego2250** [comment]
Se discutió con el grupo de backend y no se le ve la necesidad de agregar esto.
