### ISSUE TITLE
Chat al postularse

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#175]
Los chats se estan creando luego de la postulacion a una oferta de trabajo, sin embargo se esta creando un chat para cada empresa en lugar de un chat para cada postulacion nueva, es decir que si me postulo a 2 ofertas de la misma empresa el chat es el mismo, y se reenvia el mensaje inicial, lo que puede crear confusiones.

**Comment by jazurdia** [comment]
mora no lo has hecho. @Diego2250

**Comment by Diego2250** [comment]
Ya se discutió el tema en el grupo y se hará 1 chat solamente. Se modificará el mensaje que se envia pra agregar el titulo de la psotulacion.
