### ISSUE TITLE
Eliminar postulacion

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#176]
Necesito un api que con el id de la postulacion y el id del estudiante, si es que lo usan, no se si los id de postulacion son unicos para todos los estudiantes, se pueda eliminar la postulacion de dicho estudiante hacia la oferta laboral.

**Comment by markalbrand56** [comment]
Completado en #181 
Se usa en api/postulations, con método DELETE, sin body
Se necesita como query parameter el id de la postulación a eliminar

![image](https://github.com/markalbrand56/IS-Proyecto/assets/62487869/20818ad5-982f-4896-8427-4506cb2bfe76)
