### ISSUE TITLE
Orden de los chats

### ISSUE THREAD

**Issue by markalbrand56** [markalbrand56/IS-Proyecto#185]
Los chats no se están desplegando en el orden que se enviaron

![image](https://github.com/markalbrand56/IS-Proyecto/assets/62487869/a57da721-be48-497f-96e1-81ebbb20a0ad)

Este es un ejemplo, de mi cuenta personal mandé dos mensajes seguidos y después respondí desde la cuenta de la empresa. Pero la respuesta de la empresa se muestra, en ambas cuentas, antes que el mensaje que se envió antes.

Este problema se observa tanto en la rama en la que yo estoy implementando las nuevas fotos de perfil como la desplegada en Netlifly con el último PR: #184

**Comment by Diego2250** [comment]
@angelcast2002 El orden se hace desde el front o solo los pones en el orden que viene desde el api?

**Comment by angelcast2002** [comment]
El orden en el que se muestran los mensajes es tomado tal como vienen desde el api, asi mismo la hora es sobre la que mandan en el api
En el front no se hace ningun sort

**Comment by Diego2250** [comment]
listo
