### ISSUE TITLE
mejorar api

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#195]
para el api 
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/27e9e4e9-b54d-49c8-b74c-e578a9242c12)
regresar
- Foto
- Nombre
- universidad (si es estudiante)
- carrera (si es estudiante)
- mail
- telefono
- edad (si es estudiante)
- semestre (si es estudiante)

**Comment by angelcast2002** [comment]
btw actualicen la doc

**Comment by angelcast2002** [comment]
Falto el telefono

**Comment by markalbrand56** [comment]
Listo
