### ISSUE TITLE
PFP en postulantes a una oferta

### ISSUE THREAD

**Issue by Diego2250** [markalbrand56/IS-Proyecto#200]
No se esta cargando la foto de perfil del estudiante el momento de que la empresa ve los postulantes a una oferta. 

![Imagen de WhatsApp 2023-10-09 a las 21 00 59_4bb8e435](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/b1349a92-c9d1-408d-904f-2e1620eeb590)

Al inspeccionar el elemento, se ve que no se esta poniendo el src

![Imagen de WhatsApp 2023-10-09 a las 21 05 14_59829079](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/cf36741c-0326-4c0f-8101-4495db0cc22d)

**Comment by angelcast2002** [comment]
es porque en el base de datos foto esta en vacio
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/a83a6dfd-72d9-4054-b1d4-b012268a8488)
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/116ad8a1-a062-4644-b6d4-c7d18665176d)
de cualquier forma ya le puse un placeHolder
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/f92e25d3-b9bd-4c2c-8439-304293e2fe1c)

**Comment by markalbrand56** [comment]
![image](https://github.com/markalbrand56/IS-Proyecto/assets/62487869/9f8d3096-da84-4c0c-817c-827ad69eb53e)

**Comment by angelcast2002** [comment]
cambiaron el api, y su respuesta, corregido por @Kojimena
