### ISSUE TITLE
Apis para obtener la info del usuario como admin

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#218]
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/c329ba90-2df3-48d6-a11a-d54fce7d4d87)
Deberian ser post ya que necesito enviarles el id del estudiante o empresa que necesito.

**Comment by markalbrand56** [comment]
Esa ruta está pensada para devolver un listado de todos los usuarios en la aplicación. Para obtener detalles de una cuenta ya existe la ruta */users/details*. A menos que se necesiten más detalles que no sean públicos, que no debería ser el caso, no se hará una nueva ruta para esa funcionalidad. 
El único cambio que se tiene pensado intentar implementar en las rutas */admins/students* y */admins/companies* son query parameters para definir un límite de usuarios, si se deseara hacer una lista paginada de todos los usuarios de la aplicación, pero es un cambio con alta prioridad en backend.

**Comment by angelcast2002** [comment]
Pero estas rutas no regresan el estado de suspension del usuario, lo cual, como tal no debe estar en el perfil publico, pero si en la vista del administrador, y es mucho traer toda la informacion de todos los usuarios solo para saber si esta suspendido o no.

**Comment by markalbrand56** [comment]
Mmm cierto
Ok, se va a añadir esa ruta

**Comment by markalbrand56** [comment]
api/admins/details

**Comment by angelcast2002** [comment]
la documentacion esta mal.
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77862762/b1bb5349-6810-49bb-b94e-4fd972c742e0)
es admins y pusieron admin
