### ISSUE TITLE
Api para obtener las postulaciones de un estudiante siendo admin

### ISSUE THREAD

**Issue by angelcast2002** [markalbrand56/IS-Proyecto#219]

**Comment by angelcast2002** [comment]
No hay ninguna api para poder acceder a esta informacion

**Comment by markalbrand56** [comment]
A qué te referís?
Existe la ruta */offers/applicants* para que una empresa vea qué estudiantes se han postulado a su oferta laboral. La postulación del estudiante no guarda nada más que la relación de hacia que oferta se postuló. 
Al ver los aplicantes, se tiene pensado que la empresa pueda abrir el perfil del estudiante y desde el perfil mandar un mensaje, o directamente empezar una conversación on el aplicante

**Comment by angelcast2002** [comment]
My bad, era siendo admin no empresa, ya que la que actualmente esta obtiene el usuario del token, pero esto no se puede hacer cuando se es admin

**Comment by markalbrand56** [comment]
Ah, ok
Se añadirá la ruta

**Comment by angelcast2002** [comment]
necesito esta api >:(

**Comment by angelcast2002** [comment]
@Diego2250 @jazurdia

**Comment by jazurdia** [comment]
Resuelto. 
La ruta nueva se llama [POST] api/admins/GetPostulationsFromStudent

**Comment by angelcast2002** [comment]
la documentacion esta mal y no regresa las postulaciones

**Comment by angelcast2002** [comment]
![Uploading image.png…]()

**Comment by jazurdia** [comment]
La documentación fue corregida. La ruta funciona correctamente.
