### ISSUE TITLE
Tiempo completo, part time y horarios

### ISSUE THREAD

**Issue by Kojimena** [markalbrand56/IS-Proyecto#233]
Hay que agregar esos nuevos campos en ofertas

**Comment by Diego2250** [comment]
Se agregaron los camos a la DB de esta forma:

Jornada es un campo de texto de maximo 30 caracteres, hora_inicio y hora_finalizacion son de tipo TIME en y el formato es en 24 horas. Ejemplos en la imagen 

![image](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/4c00a24a-ae86-4069-a7c6-af21c159db38)

**Comment by Diego2250** [comment]
Ya se agrego a la API
