### ISSUE TITLE
Cambio en el formato de hora en detalles de postulación

### ISSUE THREAD

**Issue by Diego2250** [markalbrand56/IS-Proyecto#247]
Actualmente, se ve así la hora en la preview de una oferta: 
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/288599ee-c356-4d27-af47-48fc93366cea)
(Formato 12 horas)

Pero al entrar a ver los detalles de la oferta, se ve así
![image](https://github.com/markalbrand56/IS-Proyecto/assets/77738746/f7d252aa-5733-4b90-a08c-28e0a3c8c550)
Formato 24 horas y el AM y PM son valores fijos, por lo que si en la hora de inicio se pone una hora despues de las 11:59 AM, se mostrará 13 AM aunque en realidad deberia ser la 1 PM. 

Ya que está en la preview, se deberia hacer de la misma forma en los detalles

**Comment by angelcast2002** [comment]
Lixto
